@startuml Components Diagram

left to right direction
skinparam monochrome true

database MongoDB

node Backend {
  [Auth Service] as auth <<Node>>
  [CRUD Service] as crud <<Java>>
  [Report Service] as report
}

node Frontend {
  [Frontend Server] as front
}

node "API Gateway" {
  [AWS API\n Gateway] as gateway
}

database Redis

front <--> gateway
gateway <--> crud
gateway <--> report
gateway <--> auth

crud <--> Redis
auth <--> Redis
report <--> Redis

Redis <--> MongoDB

@enduml